Repository Vinifera-Developers/Vinifera, pull requests merged in 2024-09, with the labels that each got.

#947 Adds support for up to 32767 waypoints to be used in scenarios.
  src/extensions/display/displayext_hooks.cpp
  src/extensions/extension_hooks.cpp
  src/extensions/mapseed/mapseedext_hooks.cpp
  src/extensions/scenario/scenarioext.cpp
  src/extensions/scenario/scenarioext.h
  src/extensions/scenario/scenarioext_hooks.cpp
  src/extensions/taction/tactionext_hooks.cpp
  src/extensions/team/teamext_hooks.cpp
  src/vinifera/vinifera_defines.h
Labels: new-feature, enhancement

#342 Adds keyboard commands to reproduce the last items that were built.
  CREDITS.md
  docs/User-Interface.md
  docs/Whats-New.md
  src/extensions/command/commandext.cpp
  src/extensions/command/commandext.h
  src/extensions/command/commandext_hooks.cpp
Labels: new-feature, quality-of-life

#1060 Improvements to object pip drawing
  CREDITS.md
  docs/New-Features-and-Enhancements.md
  docs/User-Interface.md
  docs/Whats-New.md
  src/extensions/rules/rulesext.cpp
  src/extensions/rules/rulesext.h
  src/extensions/techno/technoext_hooks.cpp
  src/extensions/technotype/technotypeext.cpp
  src/extensions/technotype/technotypeext.h
  src/extensions/technotype/technotypeext_hooks.cpp
  src/extensions/tiberium/tiberiumext.cpp
  src/extensions/tiberium/tiberiumext.h
  src/new/ui/uicontrol.cpp
  src/new/ui/uicontrol.h
Labels: new-feature

#472 Changes starting unit placement to be the same as Red Alert 2.
  CREDITS.md
  docs/Miscellaneous.md
  docs/Whats-New.md
  src/extensions/scenario/scenarioext.cpp
Labels: quality-of-life
